-- Add background_context column to analyses table
-- This stores contextual background information about the claim topic
-- Generated by Perplexity API during analysis

ALTER TABLE "analyses" ADD COLUMN IF NOT EXISTS "background_context" TEXT;

